#!/bin/bash -x

set -o nounset
set -o pipefail
set -o errexit

KERNEL_VERSION=$VERSION

declare -a APT_GET_OPTS=(
	--assume-yes
	--allow-downgrades
)
export DEBEMAIL="jhathaway@wikimedia.org"
export DEBFULLNAME="Jesse Hathaway"

source /etc/os-release
IFS=' ()' read -r _ CODENAME <<<"${VERSION}"

ARTIFACTS="${ARTIFACTS:-/artifacts}"
ARTIFACTS+="/${CODENAME}"
mkdir -p "${ARTIFACTS}"

mkdir -p /source
curl -Ls "${TARBALL}" >/source/source.tar
tar xf /source/source.tar -C /source

pushd /source/*linux* >/dev/null

mkdir -p debian/certs/
cp /debian-uefi-certs.pem debian/certs
cp "/configs/${CONFIG}" .config
make olddefconfig
# COPY perf_build.sh /source/linux-${version}/

make -j "$(nproc)" deb-pkg KDEB_PKGVERSION="$(make kernelversion)-1~${ORG}${VERSION_ID}+${EXTRA_VERSION}"

cp ../*.deb "${ARTIFACTS}"

# test install
apt-get install "${APT_GET_OPTS[@]}" ../*.deb
